CREATE DATABASE IF NOT EXISTS mysite;
USE mysite;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	fullname VARCHAR(150) NOT NULL,
	username VARCHAR(80) NOT NULL UNIQUE,
	email VARCHAR(150) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	phone VARCHAR(40) NOT NULL,
	gender VARCHAR(20) NOT NULL,
	dob DATE NOT NULL,
	role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payrolls (
	id INT AUTO_INCREMENT PRIMARY KEY,
	payroll_name VARCHAR(150) NOT NULL,
	payroll_date DATE NOT NULL,
	uploaded_by VARCHAR(80) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
	id INT AUTO_INCREMENT PRIMARY KEY,
	payroll_id INT NOT NULL,
	matricule VARCHAR(80) NOT NULL,
	name VARCHAR(150) NOT NULL,
	amount DECIMAL(12, 2) NOT NULL,
	status ENUM('paid', 'unpaid') NOT NULL DEFAULT 'unpaid',
	FOREIGN KEY (payroll_id) REFERENCES payrolls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
	id INT AUTO_INCREMENT PRIMARY KEY,
	customer_id INT NOT NULL,
	paid_by VARCHAR(80) NOT NULL,
	payment_date DATETIME NOT NULL,
	FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);
